server:
  port: 8082
  
eureka:  client:    service-url:      default-zone: http://localhost:8761/
  instance:
   prefer-ip-address: true


# database specific properties
# dialect to inform hibernate which database is used

spring:  application:    name: FIXTURES-SERVICE
#to get the repo url from config server  config:    import: configserver:http://localhost:8888  profiles:    active: prod, dev
    
  
    
    
    
    
    
    
    
    
    